"""Account identity and list eligibility; passwords are generated by the server."""

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UsernameField

from . import texting_lists


class RepMembershipForm(forms.Form):
    list_types = forms.MultipleChoiceField(
        label="Texting lists", choices=texting_lists.active_choices,
        widget=forms.CheckboxSelectMultiple,
        error_messages={"required": "Choose at least one texting list."},
    )

    def __init__(self, *args, rep=None, **kwargs):
        super().__init__(*args, **kwargs)
        if rep is not None and not self.is_bound:
            # Only lists that can still be picked are shown; hidden-list memberships are kept on save.
            self.fields["list_types"].initial = list(rep.list_memberships.values_list("list_type", flat=True))


class RepCreationForm(RepMembershipForm):
    first_name = forms.CharField(max_length=150, label="First name")
    last_name = forms.CharField(max_length=150, label="Last name")
    username = UsernameField(
        max_length=150, label="Username",
        validators=get_user_model()._meta.get_field("username").validators,
        help_text="Use first.last, for example emilio.arguello.",
    )
    field_order = ["first_name", "last_name", "username", "list_types"]

    def clean_username(self):
        value = self.cleaned_data["username"]
        if get_user_model().objects.filter(username__iexact=value).exists():
            raise forms.ValidationError("This username is already in use.")
        return value
