# Generated by Django 5.2.17 on 2026-10-01 14:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reserved', 'Reserved'), ('called', 'Called'), ('blocked', 'Blocked'), ('retired', 'Retired')], default='new', max_length=12)),
                ('suppression_reason', models.CharField(blank=True, max_length=40)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_imports', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_rep_batches', to=settings.AUTH_USER_MODEL)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rep_batches', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='tracker.importbatch')),
            ],
            options={
                'ordering': ['scheduled_date', 'rep__username'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Ready'), ('in_progress', 'Call in progress'), ('done', 'Completed'), ('cancelled', 'Closed')], default='pending', max_length=14)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tracker.phonenumber')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tracker.repbatch')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('not_interested', 'Not interested'), ('do_not_call', 'Do not call'), ('no_answer', 'No answer'), ('interested', 'Interested'), ('callback_requested', 'Callback requested')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='tracker.assignment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment',), name='one_outcome_per_assignment')],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_value', models.CharField(max_length=120)),
                ('classification', models.CharField(choices=[('ready', 'Ready to call'), ('previous', 'Phone number uploaded previously'), ('duplicate', 'Duplicate in this file'), ('invalid', 'Needs correction'), ('blocked', 'Blocked from calling')], max_length=12)),
                ('message', models.CharField(blank=True, max_length=250)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='tracker.importbatch')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='tracker.phonenumber')),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('upload', 'row_number'), name='unique_upload_row')],
            },
        ),
        migrations.AddConstraint(
            model_name='repbatch',
            constraint=models.UniqueConstraint(fields=('upload', 'scheduled_date', 'rep'), name='unique_daily_rep_batch'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_progress'])), fields=('phone',), name='one_active_assignment_per_phone'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('batch', 'sequence'), name='unique_batch_sequence'),
        ),
    ]
