# Generated by Django 5.2.17 on 2026-10-01 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('gfs', 'GFS Texting'), ('ringcentral', 'Ringcentral Texting')], max_length=16)),
            ],
            options={
                'ordering': ['rep_id', 'list_type'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='list_type',
            field=models.CharField(blank=True, choices=[('gfs', 'GFS Texting'), ('ringcentral', 'Ringcentral Texting')], default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('list_type__in', ['', 'gfs', 'ringcentral'])), name='valid_import_list_type'),
        ),
        migrations.AddField(
            model_name='replistmembership',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='replistmembership',
            constraint=models.UniqueConstraint(fields=('rep', 'list_type'), name='unique_rep_list_membership'),
        ),
        migrations.AddConstraint(
            model_name='replistmembership',
            constraint=models.CheckConstraint(condition=models.Q(('list_type__in', ['gfs', 'ringcentral'])), name='valid_rep_list_membership_type'),
        ),
    ]
