# Generated by Django 5.2.17 on 2026-10-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_texting_list_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='list_type',
            field=models.CharField(blank=True, choices=[('gfs', 'GFS Texting (Donut)'), ('ringcentral', 'Ringcentral Texting (Clean)')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='replistmembership',
            name='list_type',
            field=models.CharField(choices=[('gfs', 'GFS Texting (Donut)'), ('ringcentral', 'Ringcentral Texting (Clean)')], max_length=16),
        ),
    ]
