# Generated by Django 5.2.17 on 2026-10-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_texting_list_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='include_previous',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ready'), ('in_progress', 'Call in progress'), ('done', 'Completed'), ('cancelled', 'Closed'), ('reassigned', 'Assigned again')], default='pending', max_length=14),
        ),
    ]
