# Generated by Django 5.2.17 on 2026-10-02 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_reupload_previous_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='planned_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TemplateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('list_type', models.CharField(choices=[('gfs', 'GFS Texting (Donut)'), ('ringcentral', 'Ringcentral Texting (Clean)')], max_length=16)),
                ('weekdays', models.JSONField(default=list)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('reps', models.ManyToManyField(blank=True, related_name='template_lists', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='tracker.scheduletemplate')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='template_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='tracker.templatelist'),
        ),
        migrations.AddConstraint(
            model_name='templatelist',
            constraint=models.CheckConstraint(condition=models.Q(('list_type__in', ['gfs', 'ringcentral'])), name='valid_template_list_type'),
        ),
    ]
