# Generated by Django 5.2.17 on 2026-10-02 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_schedule_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_key', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('list_type', models.CharField(choices=[('gfs', 'GFS Texting (Donut)'), ('ringcentral', 'Ringcentral Texting (Clean)')], max_length=16)),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_skips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'label', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('label_key', 'list_type', 'day'), name='unique_plan_skip'), models.CheckConstraint(condition=models.Q(('list_type__in', ['gfs', 'ringcentral'])), name='valid_plan_skip_list_type')],
            },
        ),
    ]
