# Generated by Django 5.2.17 on 2026-10-02 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_installed_lists(apps, schema_editor):
    """The two lists the app shipped with keep their keys, so all history still points at them."""
    TextingList = apps.get_model("tracker", "TextingList")
    for key, name, nickname in [("gfs", "GFS Texting", "Donut"), ("ringcentral", "Ringcentral Texting", "Clean")]:
        TextingList.objects.get_or_create(key=key, defaults={"name": name, "nickname": nickname})


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_plan_skips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name', 'pk'],
            },
        ),
        migrations.RunPython(create_installed_lists, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='valid_import_list_type',
        ),
        migrations.RemoveConstraint(
            model_name='planskip',
            name='valid_plan_skip_list_type',
        ),
        migrations.RemoveConstraint(
            model_name='replistmembership',
            name='valid_rep_list_membership_type',
        ),
        migrations.RemoveConstraint(
            model_name='templatelist',
            name='valid_template_list_type',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='list_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='planskip',
            name='list_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='replistmembership',
            name='list_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='templatelist',
            name='list_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='textinglist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
